version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |  # we'll use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
          command: pipenv install -e .
      - run:
          command: pipenv run python tests/integration/test_gsheet_loader.py

workflows:
  version: 2
  build-tap:
    jobs:
      - build:
          context: gsheets_readonly
