version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.2

jobs:
  it-tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - orb-tools/install-bats
      - checkout
      - run:
          command: |  # we'll use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
          command: pipenv install -e .
      - run:
          command: pipenv run python tests/integration/test_gsheet_loader.py
      - run:
          command: |
            PRIVATE_KEY=$(echo $PRIVATE_KEY | base64 --decode) pipenv run bats bats/cli.bats

workflows:
  version: 2
  build-tap:
    jobs:
      - it-tests:
          context: gsheets_readonly
